name: CI-Windows

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
